#!/usr/bin/env bash
#
# Install a `with-onnxruntime` wrapper into the XDG user-bin directory
# (~/.local/bin) that runs any command with ORT_DYLIB_PATH pre-set.
#
# Why: macOS dlopen does NOT search /opt/homebrew/lib by default, so the
# `sbert-onnx` / `classifier-onnx` features can't find libonnxruntime even
# after `brew install onnxruntime`. Rather than exporting ORT_DYLIB_PATH in
# every shell, install a thin wrapper once:
#
#     ./scripts/install_onnxruntime_xdg.sh
#     with-onnxruntime cargo test --features sbert-onnx -- --ignored
#
# The wrapper resolves the dylib at run time so it keeps working after
# Homebrew upgrades.
#
# Override with:  XDG_BIN=/custom/path ./scripts/install_onnxruntime_xdg.sh

set -euo pipefail

XDG_BIN="${XDG_BIN:-$HOME/.local/bin}"
WRAPPER="$XDG_BIN/with-onnxruntime"

# Resolve dylib location (Homebrew on macOS, system path on Linux).
if command -v brew >/dev/null 2>&1 && brew --prefix onnxruntime >/dev/null 2>&1; then
    DYLIB_DIR="$(brew --prefix onnxruntime)/lib"
    case "$(uname -s)" in
        Darwin) DYLIB="$DYLIB_DIR/libonnxruntime.dylib" ;;
        *)      DYLIB="$DYLIB_DIR/libonnxruntime.so"    ;;
    esac
elif [ -f /usr/local/lib/libonnxruntime.so ]; then
    DYLIB="/usr/local/lib/libonnxruntime.so"
elif [ -f /usr/lib/libonnxruntime.so ]; then
    DYLIB="/usr/lib/libonnxruntime.so"
else
    echo "error: libonnxruntime not found" >&2
    echo "  macOS: brew install onnxruntime" >&2
    echo "  Linux: install onnxruntime from https://github.com/microsoft/onnxruntime/releases" >&2
    exit 1
fi

if [ ! -f "$DYLIB" ]; then
    echo "error: resolved dylib path does not exist: $DYLIB" >&2
    exit 1
fi

mkdir -p "$XDG_BIN"

cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by scripts/install_onnxruntime_xdg.sh.
# Runs the given command with ORT_DYLIB_PATH set so the syara-x ONNX
# features can locate libonnxruntime.
export ORT_DYLIB_PATH="\${ORT_DYLIB_PATH:-$DYLIB}"
exec "\$@"
EOF
chmod +x "$WRAPPER"

echo "==> Installed: $WRAPPER"
echo "    ORT_DYLIB_PATH -> $DYLIB"
echo
echo "Usage:"
echo "    with-onnxruntime cargo test --features sbert-onnx -- --ignored"
echo
case ":$PATH:" in
    *":$XDG_BIN:"*) ;;
    *)
        echo "note: $XDG_BIN is not on PATH. Add this to your shell rc:"
        echo "    export PATH=\"\$HOME/.local/bin:\$PATH\""
        ;;
esac
